---
Name: glossary-config
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.glossaryCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "glossaryCache"

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'dnadesign/silverstripe-glossary:client/css/editor.css'

DNADesign\Glossary\Models\DefinitionContext:
  default_records:
    default:
      Name: Default
